version: '3'
services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      - "80:80"
      - "22:22"
    volumes:
      #- ./content:/var/www/html
      - ./init/init.sh:/init.sh
      - ./init/apache2.conf:/etc/apache2/apache2.conf
    links:
      - 'mysql'
    command: ["/init.sh"]
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      #MYSQL_USER: "testuser"
      #MYSQL_PASSWORD: "testpassword"
      MYSQL_DATABASE: "db"
